// Generated by https://quicktype.io

export interface Build {
  id: number
  userId: number
  championName: string
  championKey: string
  cost: number
  level: number
  items: string[]
  stats: { [key: string]: number }
}
