// Generated by https://quicktype.io

export interface Item {
  name:              string;
  id:                number;
  tier:              number;
  rank:              any[];
  buildsFrom:        any[];
  buildsInto:        number[];
  specialRecipe:     number;
  noEffects:         boolean;
  removed:           boolean;
  requiredChampion:  string;
  requiredAlly:      string;
  icon:              string;
  simpleDescription: string;
  nicknames:         any[];
  passives:          any[];
  active:            any[];
  stats:             { [key: string]: Stat };
  shop:              Shop;
  iconOverlay:       boolean;
}

export interface Shop {
  prices:      Prices;
  purchasable: boolean;
  tags:        any[];
}

export interface Prices {
  total:    number;
  combined: number;
  sell:     number;
}

export interface Stat {
  flat:            number;
  percent:         number;
  perLevel:        number;
  percentPerLevel: number;
  percentBase:     number;
  percentBonus:    number;
}
